var express = require('express');
var app = express();
var router = express.Router();
var path = require('path');
var main = require('./main/index');
var user = require('./user/index');
var admin = require('./admin/index');
var ticket = require('./ticket/index');
var movie = require('./movie/index');
var cinema = require('./cinema/index');
var market = require('./market/index');
var payment = require('./payment/index');

router.use('/', main);
router.use('/user', user);
router.use('/admin', admin);
router.use('/ticket', ticket);
router.use('/movie', movie);
router.use('/cinema', cinema);
router.use('/market', market);
router.use('/payment', payment);
module.exports = router;